apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kuard
  annotations:
    testing-key: "testing-value"
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "1"
        memory: 300Mi
      requests:
        cpu: 500m
        memory: 150Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
