apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pv
  name: nginx-pv
spec:
  containers:
  - image: nginx
    name: nginx-pv
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      hostPath:
        path: /tmp
  dnsPolicy: ClusterFirst
  restartPolicy: Never